version: "3"
services:
  db:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: testshopdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  redis:
    image: redis
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
